haskellserver:
  build: server
  # image: sjwoodman/haskell-server
  ports:
    - "9001:9001"
  stdin_open: true
  tty: true

haskellclient:
  build: client
  # image: sjwoodman/haskell-client
  links:
    - haskellserver

haskelllink:
  build: link
  # image: sjwoodman/haskell-client2
  links:
    - haskellserver
