node3:
  build: server
  stdin_open: true
  tty: true
node2:
  build: client2
  links:
    - node3
  stdin_open: true
  tty: true
node1:
  build: client
  stdin_open: true
  tty: true
  links:
    - node3
