# consumer via streamMerge
node4:
  build: node4
  stdin_open: true
  tty: true

# producers:

node3:
  build: node3
  stdin_open: true
  tty: true
  links:
    - node4

node2:
  build: node2
  stdin_open: true
  tty: true
  links:
    - node4


node1:
  build: node1
  stdin_open: true
  tty: true
  links:
    - node4
