haskellserver:
  build: server
  ports:
    - "9001:9001"
  tty: true
haskellclient2:
  build: client2
  links:
    - haskellserver
  ports:
    - "9002:9002"
haskellclient:
  build: client
  links:
    - haskellclient2
