node3:
    build: node3
    stdin_open: true
    tty: true
    ports:
      - "8082:8080"
node2:
    build: node2
    links:
      - node3
    stdin_open: true
    tty: true
    ports:
      - "8081:8080"
node1:
    build: node1
    links:
      - node2
    ports:
      - "8080:8080"
