version: '3'
services:

  haskellserver:
    build: server 
    tty: true

  haskellclient2:
    build: client2   
    depends_on:
      - haskellserver

  haskellclient:
    build: client
    depends_on:
      - haskellclient2
