haskellserver:
  build: server
  ports:
    - "9001:9001"
  stdin_open: true
  tty: true
haskellclient2:
  build: client2
  links:
    - haskellserver
  ports:
    - "9002:9002"
  stdin_open: true
haskellclient:
  build: client
  links:
    - haskellclient2
