haskellserver:
  build: server
  stdin_open: true
  tty: true
haskellclient2:
  build: client2
  links:
    - haskellserver
  stdin_open: true
  tty: true
haskellclient:
  build: client
  links:
    - haskellclient2
