version: '3'
services:

  haskellserver:
    build: server
    stdin_open: true
    tty: true

  haskellclient2:
    build: client2
    stdin_open: true
    tty: true
    depends_on:
      - haskellserver

  haskellclient:
    build: client
    depends_on:
      - haskellclient2
