apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Values.image.repository.name }}
  labels:
    app: {{ .Values.image.repository.name }}
    all: {{ .Values.striot }}
    chart: {{ template "test-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.image.repository.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.image.repository.name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.image.repository.name }}
          image: "{{ .Values.image.repository.prefix }}/{{ .Values.image.repository.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9001
              protocol: TCP
          env:
            - name: "AMQ_BROKER_SERVICE_HOST"
              value: {{ .Values.amqBroker.host }}
            - name: "HASKELL_SERVER_SERVICE_HOST"
              value: {{ .Values.sink.host }}
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
