apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.repository.name }}
# annotations:
#    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    app: {{ .Values.image.repository.name }}
    striot: {{ .Values.striot }}
    chart: {{ template "test-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: striot
      port: {{ .Values.service.port }}
      protocol: TCP
    - name: web
      protocol: TCP
      port: 8080
      targetPort: web
  selector:
    app: {{ .Values.image.repository.name }}
    release: {{ .Release.Name }}
