apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: striot
  labels:
    striot: monitor
spec:
  selector:
    matchLabels:
      striot: monitor
  endpoints:
  - port: 8080            # works for different port numbers as long as the name matches
    interval: 10s        # scrape the endpoint every 10 seconds
