apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-striot
  labels:
    prometheus: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
        striot: monitor
